tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'bat'
brew 'colordiff'
brew 'coreutils'
brew 'curl'
cask 'docker'
brew 'docker-completion'
brew 'git'
brew 'git-crypt'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar'
brew 'gnupg2'
cask 'iterm2'
brew 'fzf'
brew 'jq'
brew 'shellcheck'
brew 'warrensbox/tap/tfswitch'
brew 'the_silver_searcher'
brew 'pure'
cask 'sourcetree'
cask 'svn'
brew 'z'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-lovers'
brew 'zsh-syntax-highlighting'
cask 'font-cascadia-code'
cask 'font-droid-sans-mono-for-powerline'
cask 'font-inconsolata'
cask 'font-fira-code'
cask 'font-fira-mono'



